# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Iwashere < Formula
  desc "Context preservation tool for developers"
  homepage "https://github.com/Murchoid/iwashere"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Murchoid/iwashere/releases/download/v0.2.0/iwashere_0.2.0_darwin_amd64.tar.gz"
      sha256 "608fd7c77325435072466a70a673d89c355d14358d72d45a2817ac4e021e65f8"

      define_method(:install) do
        bin.install "iwashere"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Murchoid/iwashere/releases/download/v0.2.0/iwashere_0.2.0_darwin_arm64.tar.gz"
      sha256 "c70f27da12e3459eb3e1b70ace8e7208b311e9d2dd3c2321ffbb1bbda514c9fe"

      define_method(:install) do
        bin.install "iwashere"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Murchoid/iwashere/releases/download/v0.2.0/iwashere_0.2.0_linux_amd64.tar.gz"
      sha256 "60825c9b2d2c1f59b6f095fea75041ee2cc11a4bd3cc50ef6b5e2f821e7806a0"
      define_method(:install) do
        bin.install "iwashere"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Murchoid/iwashere/releases/download/v0.2.0/iwashere_0.2.0_linux_arm64.tar.gz"
      sha256 "c55b90420be0b1b1182c0e2c654cc6eeafdff717986a8b2be1f25d6f217afd0e"
      define_method(:install) do
        bin.install "iwashere"
      end
    end
  end

  test do
    system "#{bin}/iwashere --version"
  end
end
