# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Iwashere < Formula
  desc "Context preservation tool for developers"
  homepage "https://github.com/Murchoid/iwashere"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Murchoid/iwashere/releases/tag/v0.2.2/iwashere_0.2.2_darwin_amd64.tar.gz"
      sha256 "d103af77379b18302279da0add2cd89c667d5f46dfd8c1e674100b1782de0a71"

      define_method(:install) do
        bin.install "iwashere"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Murchoid/iwashere/releases/tag/v0.2.2/iwashere_0.2.2_darwin_arm64.tar.gz"
      sha256 "8f8337fcbdcf2483244fe17241d3f63d9876e3087115dcd998c64461e6a08e6c"

      define_method(:install) do
        bin.install "iwashere"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Murchoid/iwashere/releases/tag/v0.2.2/iwashere_0.2.2_linux_amd64.tar.gz"
      sha256 "7b18c9f92a0c1dc494a7cfd5890b66299f4f7acf026edf253bb8736ca301b1ae"
      define_method(:install) do
        bin.install "iwashere"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Murchoid/iwashere/releases/tag/v0.2.2/iwashere_0.2.2_linux_arm64.tar.gz"
      sha256 "8c1fd6d268e2240ba0763e2236613f25c80dae508e29bc87f5cf31950de69f29"
      define_method(:install) do
        bin.install "iwashere"
      end
    end
  end

  test do
    system "#{bin}/iwashere --version"
  end
end
